### PR TITLE
.gitignore, an important catch and a new method for games

### PR DESCRIPTION
**Pull request by BastiTee**
Hey Chris, thanks for your nice project. I would like to propose some extensions to it though. 
* I'd add a .gitignore file. For now I incorporated typical eclipse files and anything that is created during build 
* When trying to add a move like 'e2' you'd receive an index error. this should be catched more gracefully
* For a client I needed a convenience method to obtain the latest FEN string.

### CODE REVIEW

**Comment by cgearhart** [comment]
The error catching & .gitignore are good ideas. I'm not sure about the fen helper method though. There are already two mechanisms in the public API for getting the current FEN string - converting the Game() instance to a string (e.g., str(game) - arguably bad practice) and the fen_history list - as your helper method utilizes, (e.g., game.fen_history[-1]). Is there a need for a third mechanism, especially via a helper method (as opposed to a property)?

**Comment by BastiTee** [comment]
Public API is your decision, but it might be more intuitive to have a top level method with an obvious signature. At least I didn't thought of using str(game) and the fen_history at least hides its inner order. But that's just me.

**Comment by BastiTee** [comment]
Hey Chris. I did three more things:

- .gitignore now contains the content of the basic GitHub python ignore.
- i fixed an issue when the move input is not all lowercase, e.g. a7a8Q will return InvalidMove although a7a8q is allowed.
- I **removed the get_fen method** we discussed above.

**Comment by BastiTee** [comment]
Hey, I fixed https://github.com/cgearhart/Chessnut/issues/9

**Comment by cgearhart** [comment]
I'll review and merge tonight.

**Comment by cgearhart** [comment]
I merged the pull request and then made further modifications while addressing Issue 10. I also brought back the get_fen() method, which will eventually replace using __str__ to get the current fen string in a future release. I also changed the method so that it directly calculates the current fen string rather than relying on the fen history, since it is ambiguous what None means in the context of a FEN string, because the Game class should not be uninitialized when get_fen() is called. Let me know if that works for your needs. I'll uprev the library on pypi once I'm satisfied that I didn't break anything.

**Pull request merged**
